* Notes

** Tasks [2/4]

*** DONE program to calculate risk of a prefix.

    Each prefix can be assigned a risk.  The risk is a natural number,
    and the lower the risk, the more chances of survival Endo has.  The
    risk is defined to be:

    risk = 10 * number of incorrect pixels + length of the prefix

    Here, the number of incorrect pixels is the number of positions
    where the RGB value of the picture printed in line 206 does not
    exactly match the RGB values of the provided target picture.  Note
    again that the transparency values of bitmaps [ 0 ] at the time of
    the draw command are set to 255, and that ( 0, 0 ) is the
    upper-left and ( 599, 599 ) is the lower-right corner.  The length
    of the prefix is the number of bases that constitute the prefix.

    `risk <prefix> <source.png> <target.png>`
    incorrect pixels x
    length of prefix y
    risk 10x + y

*** TODO add cost accounting to execute.

    In addition to the risk value, we are subject to certain resource limitations. Arrow must
    perform the final process, and Arrow has very little energy left, so we must make sure that
    the submitted prefix does not cause Arrow to run out of energy before it can save Endo!
    There are two limitations:

    * The length of the DNA string (~len(dna)~) must not exceed 25
      million bases at any point of the execution process.
    * Inspecting and quoting DNA costs energy; during the execution
      process, we therefore maintain a cost counter that must not
      exceed 3 billion (3x10^9):
      + in ~pattern~ or ~template~, each base consumed has a cost of 1;
      + during ~matchreplace~,
       	+ a comparison of the current base with a constant base pattern
          has a cost of 1;
       	+ a successful search has a cost of ~n − i~, evaluated after line
          109;
       	+ a failed search has a cost of ~len(dna) − i~, evaluated
          after line 109;
       	+ however, *skips are cost-free*;
      + for a call to ~protect~ with a level of at least 1, the cost is
       	equal to the length of the returned DNA string -– however, a
       	call to protect with level 0 is cost-free.

*** TODO combine dna.{hpp, cpp} into execute.cpp.

*** DONE combine rna.{hpp, cpp} into build.cpp.

** execute

*** prefix dna found

**** From Endo.pdf

     This prefix causes the self-check image to be generated.

#+BEGIN_EXAMPLE
IIPIFFCPICICIICPIICIPPPICIIC
#+END_EXAMPLE

**** From self-check.

     If the intermediate output images are saved when running the
     self-check the following prefix is displayed in an image.

#+BEGIN_EXAMPLE
IIPIFFCPICFPPICIICCIICIPPPFIIC
#+END_EXAMPLE

     The result is the following message as the final image:

#+BEGIN_EXAMPLE
                       FUUN FIELD REPAIR GUIDE

                           FUUNTECH INC.
                        DNA RESEARCH GROUP
                          1 FUUNTECH WAY
                              RIGEL IV
                         STARDATE 90.7.65.44

IF YOU HAVE MANAGED TO ACCESS THIS MESSAGE, IT MEANS THAT YOU HAVE
FOUND A CRASH-LANDED FUUN AND ARE ATTEMPTING TO REPAIR IT.  THANK
YOU FOR YOUR EFFORT IN SAVING A FUUN.  ADAPTING A FUUN TO SURVIVE IN AN
ALIEN ENVIRONMNET REQUIRES EXTENSIVE KNOWLEDGE OF THE STRUCTURE OF
FUUN DNA.  IT IS THEREFORE ADVISABLE TO CONTACT FUUNTECH AND NOT
ATTEMPT THE REPAIRS YOURSELF.  INDEED, FUUN RNA IS SO POWERFUL THAT
INCORRECT CHANGES CAN HAVE DISATROUS CONSEQUENCES ON YOUR
PLANETARY ENVIRONMENT.  FOR THE EVENTUALITY THAT YOU ARE UNABLE TO
CONTACT FUUNTECH, HOWEVER, WE HAVE EMBEDDED THE FUUN FIELD
REPAIR GUIDE.  FOR HELP ON ACCESSING THE REPAIR TOPICS CATALOG,
PREPEND THE FOLOWING ACIDS:

                   IIPIFFCPICFPPICIICCCIICIPPPCFIIC

IF YOU HAVE DIFFICULTY SEEING YOUR SURROUNDINGS, IT MAY BE THAT THE
CELESTIAL BODY YOU ARE ON IS ORIENTED AWAY FROM ITS SUN.  TO ACTIVATE
POWERFUL GENES THAT ROTATE IT TOWARDS THE NEAREST BODY SUSTAINING
NUCLEAR FUSION, PREPEND THE FOLLOWING ACIDS:

                     IIPIFFCPICPCIICICIICIPPPPIIC

		             DON'T PANIC
#+END_EXAMPLE

*** profile

#+BEGIN_SRC sh
./execute ../endo.dna
mv gmon.out execute.gmon
gprof execute execute.gmon >execute.gprof
gprof2dot -so execute.dot execute.gprof
xdot execute.dot &
#+END_SRC

** build

*** profile

#+BEGIN_SRC sh
./build ../endo.rna
mv gmon.out build.gmon
gprof build build.gmon >build.gprof
gprof2dot -so build.dot build.gprof
xdot build.dot &
#+END_SRC
